### ISSUE TITLE
Tab stops in property name results in the snippet getting treated as simple text

### ISSUE THREAD

**Issue by ramya-rao-a** [emmetio/css-snippets-resolver#5]
From @user3323 in #3

Have a snippet like `"lsn": "li$0st-st$1yle: none". `

Due to the tab stops in the property name, the snippet is not treated as a property-value pair, instead it is treated as simple text. This is because the fail the regex test at https://github.com/emmetio/css-snippets-resolver/blob/v0.2.6/lib/snippets.js#L3

Due to this, down the line the stylesheet formatter doesn't append the `;` in the end.

I personally can't think of any scenarios where this is useful, but that maybe because I am neither a daily css or emmet user.

I'll leave it up to @user3323  and @sergeche to decide the best course of action here

**Comment by sergeche** [comment]
This is not actual use case. There are two types of possible CSS snippets: property/value aliases like `foo: bar` and plain text for code like comments or complete at-rule sections. In this case Emmet falls back to plain text properly and it’s up to user to decide how end result should look like.
